#ifndef FW_CONFIG_H
#define FW_CONFIG_H

#define FW_IS_FULLSCREEN_ENABLED 1
#define FW_IS_FULLSCREEN_CHANGE_RESOLUTION_ENABLED 1
#define FW_IS_FULLSCREEN_BORDERLESS_ENABLED FALSE

#define FW_IS_MUSIC_ENABLED 1
#define FW_IS_SOUND_READ_FILE_ENABLED 0
#define FW_SOUND_FILE_PATH "D:/path/to/example.mod"

#define FW_WINDOW_NAME "XMAS 2024 - SPECTROX & DESiRE"

#define FW_FULLSCREEN_WIDTH  1920
#define FW_FULLSCREEN_HEIGHT 1080

#define FW_WINDOW_WIDTH  692
#define FW_WINDOW_HEIGHT 540

#define FW_RENDER_WIDTH  692
#define FW_RENDER_HEIGHT 540

#define FW_STARTUP_DELAY_MILLIS 500

#define FW_SCANLINES_ENABLED FALSE
#define FW_SCANLINES_ALPHA .3f

#endif
